Reedundant/drink_me

app/models/user.rb, db/migrate/20221122205634_add_user_name_to_users.rb, db/schema.rb
created user model and migrations
=> created user model/created migration/db migrated

app/models/ingredient.rb, app/models/user.rb, app/models/user_ingredient.rb, db/migrate/20221122203733_create_user_ingredients.rb, db/schema.rb, test/models/user_ingredient_test.rb
- Generate user ingredient model
- Define associations between `user`, `user_ingredient`, and `ingredient` models
- Set validation for `user_ingredient` model
=> Generate user_ingredient model

db/migrate/20221122221922_create_custom_recipe_user_ingredients.rb, db/schema.rb, db/seeds.rb
This can/will be updated later! 
I added elements to the ingredients table so that I have something to work with when making the `user_ingredients` controller.
=> Generate Ingredient instances to add to the ingredients table

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_title.scss, app/views/pages/home.html.erb, app/views/shared/_title.html.erb
Added our Raleway font to the stylesheet!
=> Adding font-styles to our styles sheets

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/user_tools_controller.rb, app/models/tool.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/user_tools/index.html.erb, app/views/user_tools/new.html.erb, config/routes.rb, db/seeds.rb, test/controllers/user_tools_controller_test.rb
completed the user_tools controller, the route and the view, which includes a simple form and completed log in sign up functions and form
=> User tool controller

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_homebutton.scss, app/views/pages/home.html.erb, app/views/shared/_homebutton.html.erb
=> Random branch

db/migrate/20221124191908_adding_fields_to_recipe_types.rb, db/schema.rb, db/seeds.rb
Added 20 cocktail ratios to the seed file!
=> Cocktail ratio seeds

app/controllers/user_ingredients_controller.rb, app/views/layouts/application.html.erb, app/views/user_ingredients/_edit_form.html.erb, app/views/user_ingredients/_form.html.erb, app/views/user_ingredients/edit.html.erb, app/views/user_ingredients/edit_selection.html.erb, app/views/user_ingredients/index.html.erb, app/views/user_ingredients/new.html.erb, config/routes.rb, db/migrate/20221122231912_create_custom_recipes.rb, db/schema.rb, package.json, test/controllers/user_ingredients_controller_test.rb, yarn.lock
missing destroy and update method
=> User ingredients controller

app/assets/stylesheets/pages/_suggestion.scss, app/controllers/pages_controller.rb, app/views/pages/results.html.erb, app/views/pages/suggestion.html.erb, config/routes.rb
check it out suggestion not align but who cares
=> suggestion page sorta done

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_title.scss, app/views/shared/_title.html.erb
Please, let me know if we would like to keep the button as was already coded or what's seen on Figma!
=> Update homepage btn and title (pls read comment 🧌)

app/assets/stylesheets/user_ingredients/_index.scss, app/assets/stylesheets/user_ingredients/_old_index.scss, app/models/ingredient.rb, app/views/user_ingredients/index.html.erb, app/views/user_ingredients/old_index.html.erb, db/api_call_ingredients.rb, db/migrate/20221128203927_remove_category_column_from_ingredients_table.rb, db/schema.rb, db/seeds.rb
=> Get ingredients from cocktaildb api

app/javascript/controllers/index.js, app/javascript/controllers/prevent_reload_on_select_controller.js, app/views/user_ingredients/index.html.erb, db/schema.rb
Just PRing for a merge from master but its complicated
=> Burner branch v3 turbo push 

app/views/user_ingredients/index.html.erb
BRUH we made booboo but made booboo better gooder
=> Burner Branch V4 

app/controllers/user_ingredients_controller.rb, app/javascript/controllers/prevent_reload_on_select_controller.js, app/views/user_ingredients/index.html.erb
Created the appropriate AJAX methods and managed to obtain proper url information en plus
=> Managed to complete the AJAX challenge successfully

app/javascript/controllers/prevent_reload_on_select_controller.js, app/views/user_ingredients/index.html.erb
Managed to limit user choice to 5. We can change the number later and also implement an alert for when they choose too many.
=> successfully managed to limit user's choices of ingredients to 5

app/controllers/recipes_controller.rb
=> Heroku hot fix is live

app/assets/images/svg-hamburger.svg, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, app/views/pages/suggestion.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb
nav bar is set to go just waiting for search controller to implement hidden feature
=> updated the nav bar

app/controllers/recipes_controller.rb
displays results if multi-ingredient query doesn't work
=> Created a new query 

app/controllers/recipes_controller.rb, app/views/recipes/codex.html.erb, config/routes.rb
=> Created a Cocktail Codex

app/controllers/recipes_controller.rb, app/views/recipes/random.html.erb, config/routes.rb
Created a Random Cocktail doo dad. PLS APPROVE.
=> Created a Random Cocktail thing

app/views/recipes/show.html.erb
=> Made instructions bulleted

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
made fonts in navbar skinnier and social distance the letters
=> changed font and spacing

public/404.html
=> edited 404/500 error pages

app/assets/stylesheets/components/_navbar.scss, app/views/devise/registrations/new.html.erb
changed spacing in font navbar
=> Making navbar look prettier

app/assets/stylesheets/application.scss, app/assets/stylesheets/devise/_form.scss, app/models/user.rb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> Style user forms

config/environments/production.rb
=> DNS set up

app/views/recipes/random.html.erb
=> FIX RANDOM RECIPE PAGE: Add .r-container to /random html page

app/views/recipes/random.html.erb
Add .recipe__btn class to btn in random.html.erb
=> Fix button in "Try your luck" page

app/assets/stylesheets/recipes/_show.scss, app/views/shared/_navbar.html.erb
PLS APPROVE PLS I BEG PLS I AM INSANE PLS
=> Added a popular button to nav bar and changed recipe text size

app/assets/images/svg-hamburger.svg, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/recipes/_index.scss, app/assets/stylesheets/recipes/_show.scss, app/assets/stylesheets/user_ingredients/_index.scss, app/views/shared/_navbar.html.erb
- removed bullet point beside hamburger menu
- shrinked the size of the hamburger bars so that they're slim 
- make hamburger menu less bright so that it doesn't take too much attention
=> Remove blue when btn clicked 

app/controllers/application_controller.rb
=> Hopefully the final set up for our url

app/assets/stylesheets/recipes/_index.scss
=> Add border radius to banners

app/assets/stylesheets/components/_alert.scss
=> Style flashes with blur

public/404.html, public/500.html
=> Finding little bugs

app/controllers/user_ingredients_controller.rb
=> Fixed our Users all sharing the same instance of ingredients

app/assets/stylesheets/pages/_ioc.scss, app/views/pages/ioc.html.erb, app/views/recipes/random.html.erb
Changed doorway text and random button text and route
=> Doorway text/Random button

app/assets/stylesheets/pages/_title.scss
=> fixed title page button
